### ISSUE TITLE
I use Windows 11. And I got the Clion CMAKE error.

### ISSUE THREAD

**Issue by Smart-Bob** [MrYsLab/Telemetrix4RpiPico#14] opened 2022-11-19 11:10 UTC
"C:\Program Files\JetBrains\CLion 2022.2.4\bin\cmake\win\bin\cmake.exe" --build D:\Clion\cmake-build-debug --target Clion -j 6
[0/1] Re-running CMake...
-- Configuring done
CMake Error at CMakeLists.txt:7 (add_executable):
  No SOURCES given to target: Assignment2.c

CMake Generate step failed.  Build files cannot be regenerated correctly.
ninja: error: rebuilding 'build.ninja': subcommand failed
FAILED: build.ninja 
"C:\Program Files\JetBrains\CLion 2022.2.4\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -SD:\Clion -BD:\Clion\cmake-build-debug

**Comment by MrYsLab** [comment] 2022-11-19 16:16
@Smart-Bob I don't have Windows 11, and I usually do not use Windows for development, but to test, I set up CLion in a Windows 10 virtual machine (VirtualBox). Below is a screenshot showing CMake succeeding. I looked for a file called Assignement2.c in my environment, and it does not exist, so I do not know if that is generated due to using Windows 11 or for some other reason.
I am sorry I could not provide an answer. Perhaps you could try running an Ubuntu virtual machine.

![Screenshot from 2022-11-19 11-02-54](https://user-images.githubusercontent.com/5189838/202860733-fce2a6ae-a3b1-45fb-8b6a-325b6bfcc6b4.png)

**Comment by MrYsLab** [comment] 2022-11-19 16:47
I just installed Windows 11 as a virtual machine and had no issues. Here are the steps I used to install and run CMake:
1. I[ downloaded and installed the latest CLion](https://www.jetbrains.com/clion/download/#section=linux).
2. I [downloaded and installed the arm toolchain.](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads) At the end of the installation, I clicked on all the checkboxes in the dialog box.
3. I installed the Pico SDK as per section 2.1 of[ "Getting Started With The Raspberry Pi Pico](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf)."
4. I opened CLion and installed Telemetrix4RpiPico using the Get From VCS option.
5. In CLion CMake settings, I set the Environment setting to **PICO_SDK_PATH=C:\Users\Alan Yorinks\pico\pico-SDK**
6. I then ran CMake, and it succeeded.

I hope this helps.

**Comment by Smart-Bob** [comment] 2022-11-20 04:44
Okay, Now I got it, I know the problem, it is I forget to write the folder name.
Now, I have got this new error.

====================[ Build | Clion | Debug ]===================================
"C:\Program Files\JetBrains\CLion 2022.2.4\bin\cmake\win\bin\cmake.exe" --build D:\Clion\cmake-build-debug --target Clion -j 6
[1/1] Linking C executable Clion.exe
FAILED: Clion.exe 
cmd.exe /C "cd . && C:\PROGRA~1\JETBRA~1\CLION2~1.4\bin\mingw\bin\gcc.exe -g  CMakeFiles/Clion.dir/MyCode.c.obj -o Clion.exe -Wl,--out-implib,libClion.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:\Program Files\JetBrains\CLion 2022.2.4\bin\mingw\bin/ld.exe: cannot open output file Clion.exe: Permission denied
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by MrYsLab** [comment] 2022-11-20 14:52
Can you compile and run the examples described in the [Getting Started ](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf#%5B%7B%22num%22%3A54%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C115%2C645.754%2Cnull%5D)manual?

If the answer is yes, compare the build settings in CLion for the examples project and Telemetrix.

I searched Google for: "client cannot open output file Clion.exe: Permission denied" and found several answers. The most prevalent one suggested turning off virus checking. If you are using a virus checker, try turning it off.

**Comment by Smart-Bob** [comment] 2022-11-21 05:38
Okay, Let me do it

**Comment by MrYsLab** [comment] 2022-11-22 16:31
I am not sure if you have solved your issue or not. I am closing this issue since I cannot reproduce it here. If you have further questions, reply here, and I will see them.

**Closed as completed by MrYsLab** 2022-11-22 16:31 UTC
