### ISSUE TITLE
UART over GP0/GP1

### ISSUE THREAD

**Issue by mklomp** [MrYsLab/Telemetrix4RpiPico#16] opened 2023-03-02 13:33 UTC
It looks like it currently is not possible to have the UART serial communication over GP0/GP1. So Telemetrix only works using a USB cable. By default this is also the case for the REPL of MicroPython. WIth MicroPython you can still enable UART over GP0/GP1 as well. Is there also something in Telemetrix so I can connect without USB cable?

**Comment by MrYsLab** [comment] 2023-03-02 15:51
The library currently only supports serial through USB. Adding GPIO serial support adds a level of complexity I am not prepared to support. 

Since there is no simple way to configure a .UF2 image dynamically, the user would need to recompile after modifying the code. Telemetrix4RpiPico uses the Raspberry Pi C-SDK, and setting up a development environment is non-trivial. I use the CLion IDE for development, and for some reason, the MS Code IDE cannot take my code, including the CMake files, and build it successfully. I tried to figure out why but could not find the cause. There is some internal structure generated by the IDEs that are incompatible.

The WiFi version of the library does not have the problem of compiling since I used the Arduino Core library for the Pico for that version. The Arduino Core was unavailable when I developed Telemetrix4RpiPico, so the C-SDK was selected.

I'm sorry, but I won't be able to help in this case.

**Comment by MrYsLab** [comment] 2023-03-03 15:51
@mklomp I am closing this issue, but if you want to try and modify the source to support this feature, please let me know, and I will supply any information you need. 

[CLion](https://www.jetbrains.com/clion/) has a 30-day free trial, and if you have published any open-source software, JetBrains will offer a free one-year subscription that is renewable. 

If you want to try debugging the issue with Microsoft Code, that would be great, but as I mentioned, I tried and failed, so that it may be challenging.

**Closed as completed by MrYsLab** 2023-03-03 15:51 UTC
Labels: wontfix

**Comment by mklomp** [comment] 2023-03-05 13:40
Hi @MrYsLab. Thanks for the explanation. Too bad it so hard to get a development environment to work. For me an env withoudt ide would already suffice.

I think for now I will try to get this working on the wifi version by disabling wifi and using the uart over the pins. Not sure, but it feels easier for me to get a working version. Any thoughts are welcome!

**Comment by MrYsLab** [comment] 2023-03-05 16:00
If you want to try and modify the wifi version, [here is a page ](https://arduino-pico.readthedocs.io/en/latest/serial.html)from the pico library's documentation that may help.

You must modify both the setup and loop functions currently using the TCP/IP client. To write to the UART you selected, you must modify the **_client._** calls to either Serial1 or Serial2.

The Python side should automatically recognize the COM port; if not, you must manually add the code to specify the COM port.

Good luck.
